image: otrs4ci

stages:
  - test
  - deploy

job_unit_otrs_Znuny4OTRSRepo:
  stage: test
  script:
    - env
    - pwd
    - /run.sh
    - su -c "git clone https://github.com/OTRS/module-tools.git" -s /bin/bash otrs
    - su -c "module-tools/link.pl . /opt/otrs/" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/znuny.AdvancedPackageManagerInstallSOPM.pl /opt/otrs/Znuny4OTRS-Repo.sopm" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.UnitTest.pl -n UnitTest/Email/Znuny4OTRSRepo/SimpleMailValidate" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.UnitTest.pl -n Znuny4OTRSRepo" -s /bin/bash otrs

job_deploy_otrs_Znuny4OTRSRepo:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-Repo.git
