image: registry.znuny.com/znuny/docker-otrs4ci:latest

services:
  - name: registry.znuny.com/znuny/docker-mysql-utf8:latest
    alias: mysql

stages:
  - test
  - deploy

job_unit_otrs_Znuny4OTRSRepo:
  stage: test
  script:
    - env
    - pwd
    - /run.sh
    - su -c "perl /opt/otrs/bin/znuny.AdvancedPackageManagerInstallSOPM.pl /opt/otrs/Znuny4OTRS-Repo.sopm" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.UnitTest.pl -n UnitTest/Email/Znuny4OTRSRepo/SimpleMailValidate" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.UnitTest.pl -n Znuny4OTRSRepo" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.UnitTest.pl -n Znuny4OTRSRepo/UnitTest/DynamicFieldsConfigExport" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.UnitTest.pl -n Znuny4OTRSRepo/UnitTest/DynamicFieldsScreenConfigImportExport" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.UnitTest.pl -n Znuny4OTRSRepo/UnitTest/ValidDynamicFieldScreenListGet" -s /bin/bash otrs

job_deploy_otrs_Znuny4OTRSRepo:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-Repo.git
