image: registry.znuny.com/znuny/internal/docker-otrs5ci:stable

stages:
  - test
  - manual
  - deploy

mysql:
  stage: test
  services:
    - name: docker.io/elgalu/selenium:latest
    - name: registry.znuny.com/znuny/internal/docker-mysql:stable
      alias: mysql
  variables:
    SELENIUM_SCREENSHOTS: 'true'
    SELENIUM_SCREENSHOTS_FUNCTIONS: 'AgentRequest, CustomerRequest'
  artifacts:
    expire_in: 1 week
#    when: on_failure
    when: always
    untracked: true
  script:
    - env
    - pwd
    - /run.sh
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Znuny4OTRS::AdvancedPackageManager::InstallSOPM /opt/otrs/Znuny4OTRS-Repo.sopm" -s /bin/bash otrs
    - /unittest.sh

oracle:
  stage: test
  services:
    - name: docker.io/elgalu/selenium:latest
    - name: registry.znuny.com/znuny/internal/docker-oracle:stable
      alias: oracle
  variables:
    SELENIUM_SCREENSHOTS: 'true'
    SELENIUM_SCREENSHOTS_FUNCTIONS: 'AgentRequest, CustomerRequest'
  artifacts:
    expire_in: 1 week
#    when: on_failure
    when: always
    untracked: true
  script:
    - env
    - pwd
    - /run.sh
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Znuny4OTRS::AdvancedPackageManager::InstallSOPM /opt/otrs/Znuny4OTRS-Repo.sopm" -s /bin/bash otrs
    - /unittest.sh

postgresql:
  stage: test
  services:
    - name: docker.io/elgalu/selenium:latest
    - name: registry.znuny.com/znuny/internal/docker-postgresql:stable
      alias: postgresql
  variables:
    SELENIUM_SCREENSHOTS: 'true'
    SELENIUM_SCREENSHOTS_FUNCTIONS: 'AgentRequest, CustomerRequest'
  artifacts:
    expire_in: 1 week
#    when: on_failure
    when: always
    untracked: true
  script:
    - env
    - pwd
    - /run.sh
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Znuny4OTRS::AdvancedPackageManager::InstallSOPM /opt/otrs/Znuny4OTRS-Repo.sopm" -s /bin/bash otrs
    - /unittest.sh

manual:
  stage: manual
  image: registry.znuny.com/znuny/internal/docker-pandoc:stable
  artifacts:
    paths:
      - ./*.pdf
    expire_in: 1 hrs
  script:
    - date

deploy:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-Repo.git
